apiVersion: v1
kind: Service
metadata:
  name: securesupply
  namespace: securesupply
spec:
  selector:
    app.kubernetes.io/name: securesupply

  ports:
    - port: 80
      targetPort: 8080

  type: ClusterIP
